version: 1.2
workflows:
  - subclass: CWL
    primaryDescriptorPath: /borrowed_code/cwl_tool_wrapper_workflow.cwl
    testParameterFiles:
      - /borrowed_code/allele_inputs.yml
  - subclass: WDL
    primaryDescriptorPath: /ld-pruning/ld-pruning-wf.wdl
    testParameterFiles:
      - /ld-pruning/ld-pruning-terra.json
    filters:
      branches: 
        - branch**